In [15]:
import pandas as pd
import random as rd
df_daily_activity = pd.read_csv("Daily.Activity.csv")
df_sleep_day = pd.read_csv("Sleep.Day.csv")
df_weight_log = pd.read_csv("Weight.Log.csv")

In [16]:
df_weight_log

,Customer_ID,Date,Day_of_Week,Date.1,Time,Weight_Kg,Weight_Pounds,Fat,BMI,Is_Manual_Report,Manual_Report,Log_Id
0,1.503960e+09,5/2/2016 23:59:59,Monday,5/2/2016,23:59:59,52.60,115.96,22,22.65,True,1.0,1.462234e+12
1,1.927972e+09,4/13/2016 1:08:52,Wednesday,4/13/2016,1:08:52,133.50,294.32,NaN,47.54,False,2.0,1.460510e+12
2,2.873213e+09,4/21/2016 23:59:59,Thursday,4/21/2016,23:59:59,56.70,125.00,NaN,21.45,True,1.0,1.461283e+12
3,2.873213e+09,5/12/2016 23:59:59,Thursday,5/12/2016,23:59:59,57.30,126.32,NaN,21.69,True,1.0,1.463098e+12
4,4.319704e+09,4/17/2016 23:59:59,Sunday,4/17/2016,23:59:59,72.40,159.61,25,27.45,True,1.0,1.460938e+12
...,...,...,...,...,...,...,...,...,...,...,...,...
154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN
158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN

In [17]:
df_weight_log = df_weight_log.dropna(subset="Customer_ID")
df_weight_log["Date"] = pd.to_datetime(df_weight_log["Date"])
df_weight_log["Day_of_Week"] = df_weight_log["Date"].dt.day_name()
df_weight_log["Date.1"] = df_weight_log["Date"].dt.date
df_weight_log["Time"] = df_weight_log["Date"].dt.time
df_weight_log["Weight_Kg"] = pd.to_numeric(df_weight_log["Weight_Kg"])
df_weight_log["Weight_Pounds"] = pd.to_numeric(df_weight_log["Weight_Pounds"])
df_weight_log["Fat"] = pd.to_numeric(df_weight_log["Fat"])
df_weight_log["BMI"] = pd.to_numeric(df_weight_log["BMI"])
df_weight_log["Fat"] = df_weight_log["Fat"].apply(lambda x:rd.randint(10,40) if pd.isna(x) else x)
df_weight_log.info()

<class 'pandas.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       66 non-null     float64
 1   Date              66 non-null     datetime64[us]
 2   Day_of_Week       66 non-null     str
 3   Date.1            66 non-null     object
 4   Time              66 non-null     object
 5   Weight_Kg         66 non-null     float64
 6   Weight_Pounds     66 non-null     float64
 7   Fat               66 non-null     float64
 8   BMI               66 non-null     float64
 9   Is_Manual_Report  66 non-null     object
 10  Manual_Report     66 non-null     float64
 11  Log_Id            66 non-null     float64
dtypes: datetime64[us](1), float64(7), object(3), str(1)
memory usage: 6.8+ KB

In [18]:
df_weight_log

,Customer_ID,Date,Day_of_Week,Date.1,Time,Weight_Kg,Weight_Pounds,Fat,BMI,Is_Manual_Report,Manual_Report,Log_Id
0,1.503960e+09,2016-05-02 23:59:59,Monday,2016-05-02,23:59:59,52.6,115.96,22.0,22.65,True,1.0,1.462234e+12
1,1.927972e+09,2016-04-13 01:08:52,Wednesday,2016-04-13,01:08:52,133.5,294.32,21.0,47.54,False,2.0,1.460510e+12
2,2.873213e+09,2016-04-21 23:59:59,Thursday,2016-04-21,23:59:59,56.7,125.00,36.0,21.45,True,1.0,1.461283e+12
3,2.873213e+09,2016-05-12 23:59:59,Thursday,2016-05-12,23:59:59,57.3,126.32,19.0,21.69,True,1.0,1.463098e+12
4,4.319704e+09,2016-04-17 23:59:59,Sunday,2016-04-17,23:59:59,72.4,159.61,25.0,27.45,True,1.0,1.460938e+12
...,...,...,...,...,...,...,...,...,...,...,...,...
61,8.877689e+09,2016-05-06 06:43:35,Friday,2016-05-06,06:43:35,85.0,187.39,34.0,25.44,False,2.0,1.462517e+12
62,8.877689e+09,2016-05-08 07:35:53,Sunday,2016-05-08,07:35:53,85.4,188.27,12.0,25.56,False,2.0,1.462693e+12
63,8.877689e+09,2016-05-09 06:39:44,Monday,2016-05-09,06:39:44,85.5,188.50,34.0,25.61,False,2.0,1.462776e+12
64,8.877689e+09,2016-05-11 06:51:47,Wednesday,2016-05-11,06:51:47,85.4,188.27,35.0,25.56,False,2.0,1.462950e+12
65,8.877689e+09,2016-05-12 06:42:53,Thursday,2016-05-12,06:42:53,84.0,185.19,21.0,25.14,False,2.0,1.463035e+12

In [19]:
df_daily_activity.info()

<class 'pandas.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Customer_ID                 940 non-null    int64
 1   Activity_Date               940 non-null    str
 2   Day_of_Week                 940 non-null    str
 3   Total_Steps                 940 non-null    int64
 4   Total_Distance              940 non-null    float64
 5   Tracker_Distance            940 non-null    float64
 6   Very_Active_Distance        940 non-null    float64
 7   Moderately_Active_Distance  940 non-null    float64
 8   Light_Active_Distance       940 non-null    float64
 9   Sedentary_Active_Distance   940 non-null    float64
 10  Very_Active_Minutes         940 non-null    int64
 11  Fairly_Active_Minutes       940 non-null    int64
 12  Lightly_Active_Minutes      940 non-null    int64
 13  Sedentary_Minutes           940 non-null    int64
 14  Calories                    940 non-null    int64
dtypes: float64(6), int64(7), str(2)
memory usage: 124.9 KB

In [20]:
df_daily_activity["Activity_Date"] = pd.to_datetime(df_daily_activity["Activity_Date"])
df_daily_activity["Day_of_Week"] = df_daily_activity["Activity_Date"].dt.day_name()
df_daily_activity

,Customer_ID,Activity_Date,Day_of_Week,Total_Steps,Total_Distance,Tracker_Distance,Very_Active_Distance,Moderately_Active_Distance,Light_Active_Distance,Sedentary_Active_Distance,Very_Active_Minutes,Fairly_Active_Minutes,Lightly_Active_Minutes,Sedentary_Minutes,Calories
0,1503960366,2016-04-12,Tuesday,13162,8.50,8.50,1.88,0.55,6.06,0.00,25,13,328,728,1985
1,1503960366,2016-04-13,Wednesday,10735,6.97,6.97,1.57,0.69,4.71,0.00,21,19,217,776,1797
2,1503960366,2016-04-14,Thursday,10460,6.74,6.74,2.44,0.40,3.91,0.00,30,11,181,1218,1776
3,1503960366,2016-04-15,Friday,9762,6.28,6.28,2.14,1.26,2.83,0.00,29,34,209,726,1745
4,1503960366,2016-04-16,Saturday,12669,8.16,8.16,2.71,0.41,5.04,0.00,36,10,221,773,1863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,2016-05-08,Sunday,10686,8.11,8.11,1.08,0.20,6.80,0.00,17,4,245,1174,2847
936,8877689391,2016-05-09,Monday,20226,18.25,18.25,11.10,0.80,6.24,0.05,73,19,217,1131,3710
937,8877689391,2016-05-10,Tuesday,10733,8.15,8.15,1.35,0.46,6.28,0.00,18,11,224,1187,2832
938,8877689391,2016-05-11,Wednesday,21420,19.56,19.56,13.22,0.41,5.89,0.00,88,12,213,1127,3832
939,8877689391,2016-05-12,Thursday,8064,6.12,6.12,1.82,0.04,4.25,0.00,23,1,137,770,1849

In [21]:
df_sleep_day

,Customer_Id,Sleep_Day,Day_of_Week,Total_Sleep_Records,Total_Minutes_Asleep,Total_Time_In_Bed
0,1503960366,4/12/2016,Tuesday,1,327,346
1,1503960366,4/13/2016,Wednesday,2,384,407
2,1503960366,4/15/2016,Friday,1,412,442
3,1503960366,4/16/2016,Saturday,2,340,367
4,1503960366,4/17/2016,Sunday,1,700,712
...,...,...,...,...,...,...
405,8792009665,4/30/2016,Saturday,1,343,360
406,8792009665,5/1/2016,Sunday,1,503,527
407,8792009665,5/2/2016,Monday,1,415,423
408,8792009665,5/3/2016,Tuesday,1,516,545
409,8792009665,5/4/2016,Wednesday,1,439,463

In [27]:
df_sleep_day["Sleep_Day"] = pd.to_datetime(df_sleep_day["Sleep_Day"])
df_sleep_day["Day_of_Week"] = df_sleep_day["Sleep_Day"].dt.day_name()
df_sleep_day

,Customer_Id,Sleep_Day,Day_of_Week,Total_Sleep_Records,Total_Minutes_Asleep,Total_Time_In_Bed
0,1503960366,2016-04-12,Tuesday,1,327,346
1,1503960366,2016-04-13,Wednesday,2,384,407
2,1503960366,2016-04-15,Friday,1,412,442
3,1503960366,2016-04-16,Saturday,2,340,367
4,1503960366,2016-04-17,Sunday,1,700,712
...,...,...,...,...,...,...
405,8792009665,2016-04-30,Saturday,1,343,360
406,8792009665,2016-05-01,Sunday,1,503,527
407,8792009665,2016-05-02,Monday,1,415,423
408,8792009665,2016-05-03,Tuesday,1,516,545
409,8792009665,2016-05-04,Wednesday,1,439,463

In [28]:
df_sleep_day.info()

<class 'pandas.DataFrame'>
RangeIndex: 410 entries, 0 to 409
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_Id           410 non-null    int64
 1   Sleep_Day             410 non-null    datetime64[us]
 2   Day_of_Week           410 non-null    str
 3   Total_Sleep_Records   410 non-null    int64
 4   Total_Minutes_Asleep  410 non-null    int64
 5   Total_Time_In_Bed     410 non-null    int64
dtypes: datetime64[us](1), int64(4), str(1)
memory usage: 22.2 KB

In [30]:
df_sleep_day = df_sleep_day.drop_duplicates()
df_daily_activity = df_daily_activity.drop_duplicates()
df_weight_log = df_weight_log.drop_duplicates()

In [33]:
df_weight_log.info()

<class 'pandas.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       66 non-null     float64
 1   Date              66 non-null     datetime64[us]
 2   Day_of_Week       66 non-null     str
 3   Date.1            66 non-null     object
 4   Time              66 non-null     object
 5   Weight_Kg         66 non-null     float64
 6   Weight_Pounds     66 non-null     float64
 7   Fat               66 non-null     float64
 8   BMI               66 non-null     float64
 9   Is_Manual_Report  66 non-null     object
 10  Manual_Report     66 non-null     float64
 11  Log_Id            66 non-null     float64
dtypes: datetime64[us](1), float64(7), object(3), str(1)
memory usage: 6.8+ KB

In [29]:
df_daily_activity.to_csv("C:/Users/USER/Pictures/Data Analysis/Power BI/Daily_activity.csv", index=False)
df_weight_log.to_csv("C:/Users/USER/Pictures/Data Analysis/Power BI/Weight_log.csv", index=False)
df_sleep_day.to_csv("C:/Users/USER/Pictures/Data Analysis/Power BI/Sleep_day.csv", index=False)